name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Push to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "your-username"

        git clone https://user:$HF_TOKEN@huggingface.co/spaces/gvrraghav/OpenAI-Chatbot-Query-App hf_space
        rsync -av --exclude=.git ./ hf_space/

        cd hf_space
        git add .
        git commit -m "Auto deploy" || echo "No changes to commit"
        git pull origin main --rebase
        git push origin main
